##____  _                 _      ____                      _               _
##  / ___|(_)_ __ ___  _ __ | | ___| __ ) _ __ ___   __ _  __| | ___ __ _ ___| |_
#    \___ \| | '_ ` _ \| '_ \| |/ _ \  _ \| '__/ _ \ / _` |/ _` |/ __/ _` / __| __|
##    ___) | | | | | | | |_) | |  __/ |_) | | | (_) | (_| | (_| | (_| (_| \__ \ |_
#    |____/|_|_| |_| |_| .__/|_|\___|____/|_|  \___/ \__,_|\__,_|\___\__,_|___/\__|
#    |_|

# 配置广播间隔（20 = 1秒）
# Config broadcast interval (20tick = 1s)
broadcast:
  interval: 2000